// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7WJtbHM8kHVuTv59DBmELgBY9Xo1ze-0',
    appId: '1:341513115380:web:9180488a128589630870a1',
    messagingSenderId: '341513115380',
    projectId: 'fresh-mart-app',
    authDomain: 'fresh-mart-app.firebaseapp.com',
    storageBucket: 'fresh-mart-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlbfoEskv8bBnUUDbpeSPgI7IwzhP7ptI',
    appId: '1:341513115380:android:68d49001b07f64420870a1',
    messagingSenderId: '341513115380',
    projectId: 'fresh-mart-app',
    storageBucket: 'fresh-mart-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQMOfaSR6YpZlPd2n1unmHjnWG2EcEkKI',
    appId: '1:341513115380:ios:ca71f7805376db8c0870a1',
    messagingSenderId: '341513115380',
    projectId: 'fresh-mart-app',
    storageBucket: 'fresh-mart-app.appspot.com',
    iosBundleId: 'com.example.freshMartApp',
  );
}
